### ISSUE TITLE
Stackoverflow for invalid `ENV` statement

### ISSUE THREAD

**Issue by RunDevelopment** [rcjsuen/dockerfile-language-server-nodejs#246] opened 2020-11-30 14:00 UTC
I'm using VS Code's Docker extension which uses your language server. I noticed that syntax highlighting breaks for the input:

```dockerfile
ENV DEBIAN_FRONTEND \
noninteractive
```

The output panel logs:

```
[Error - 2:50:00 PM] Request textDocument/semanticTokens failed.
  Message: Request textDocument/semanticTokens failed with message: Maximum call stack size exceeded
  Code: -32603 
```

---

This is invalid code, so I can understand if this issue was closed as a non-issue. I reported it anyway because the underlying issue might also affect valid code.

**Comment by rcjsuen** [comment] 2020-12-18 13:45
@RunDevelopment Thank you for opening this bug report. Apologies for not getting back to you until now. I am able to reproduce this issue in VS Code.

Looks like this has been fixed by https://github.com/rcjsuen/dockerfile-language-service/issues/76 so the Docker extension will be able to pick this up when I make a new release.

I'll leave this open for now until the change gets rolled into the language server itself.

**Comment by rcjsuen** [comment] 2020-12-25 13:20
@RunDevelopment The fix is now live in `master`. Thanks again for your bug report!

**Closed** 2020-12-25 13:19 UTC
Labels: bug

**Comment by rcjsuen** [comment] 2020-12-26 15:17
@RunDevelopment I've opened a pull request with VS Code's Docker extension to get the new release adopted, see https://github.com/microsoft/vscode-docker/pull/2585.

**Comment by RunDevelopment** [comment] 2020-12-26 15:25
Thank you @rcjsuen!
